#ifndef MACROS_H
#define MACROS_H

//DELAY
#define DELAY 50000

//DISPLAY MACROS

#define HEIGHT       30
#define WIDTH        60
#define BORDERTHICK  2
#define LEDBORDER    'R'
#define LEDSNAKE     'G'
#define LEDTEXT      'G'
#define LEDNOTEXT    ' '
#define LEDCOLLISON  'Y'
#define LEDFOOD      'Y'
#define LEDOFF       ' '

//MOVE MACROS
#define UP           1
#define DOWN         3
#define LEFT         4
#define RIGHT        2
#define START        5
#define PAUSE        42

//SNAKE MACROS
#define STARTY       HEIGHT/2
#define STARTX       WIDTH/2
#define SNAKELENGTH  3

//PIXEL SYMBOL MACROS
/*#define PIXELSLASH      {{"     "},{"    G"},{"   G "},{"  G  "},{" G   "},{"G    "},{"     "}}
#define PIXELCOLON      {{"     "},{" GG  "},{" GG  "},{"     "},{" GG  "},{" GG  "},{"     "}}
#define PIXELQUESTION   {{" GGG "},{"G   G"},{"    G"},{"   G "},{"  G  "},{"     "},{"  G  "}}
#define PIXEL0          {{" GGG "},{"G   G"},{"G  GG"},{"G G G"},{"GG  G"},{"G   G"},{" GGG "}}
#define PIXEL1          {{"  G  "},{" GG  "},{"  G  "},{"  G  "},{"  G  "},{"  G  "},{" GGG "}}
#define PIXEL2          {{" GGG "},{"G   G"},{"    G"},{"   G "},{"  G  "},{" G   "},{"GGGGG"}}
#define PIXEL3          {{"GGGGG"},{"   G "},{"  G  "},{"   G "},{"    G"},{"G   G"},{" GGG "}}
#define PIXEL4          {{"   G "},{"  GG "},{" G G "},{"G  G "},{"GGGGG"},{"   G "},{"   G "}}
#define PIXEL5          {{"GGGGG"},{"G    "},{"GGGG "},{"    G"},{"    G"},{"G   G"},{" GGG "}}
#define PIXEL6          {{"  GG "},{" G   "},{"G    "},{"GGGG "},{"G   G"},{" GGG "},{" GGG "}}
#define PIXEL7          {{"GGGGG"},{"    G"},{"   G "},{"  G  "},{" G   "},{" G   "},{" G   "}}
#define PIXEL8          {{" GGG "},{"G   G"},{"G   G"},{" GGG "},{"G   G"},{"G   G"},{" GGG "}}
#define PIXEL9          {{" GGG "},{"G   G"},{"G   G"},{" GGGG"},{"    G"},{"   G "},{" GG  "}}
#define PIXELA          {{" GGG "},{"G   G"},{"G   G"},{"G   G"},{"GGGGG"},{"G   G"},{"G   G"}}
#define PIXELC          {{" GGG "},{"G   G"},{"G    "},{"G    "},{"G    "},{"G   G"},{" GGG "}}
#define PIXELE          {{"GGGGG"},{"G    "},{"G    "},{"GGGG "},{"G    "},{"G    "},{"GGGGG"}}
#define PIXELG          {{" GGG "},{"G   G"},{"G    "},{"G GGG"},{"G   G"},{"G   G"},{" GGGG"}}
#define PIXELI          {{" GGG "},{"  G  "},{"  G  "},{"  G  "},{"  G  "},{"  G  "},{" GGG "}}
#define PIXELM          {{"G   G"},{"GG GG"},{"G G G"},{"G G G"},{"G   G"},{"G   G"},{"G   G"}}
#define PIXELN          {{"G   G"},{"G   G"},{"GG  G"},{"G G G"},{"G  GG"},{"G   G"},{"G   G"}}
#define PIXELO          {{" GGG "},{"G   G"},{"G   G"},{"G   G"},{"G   G"},{"G   G"},{" GGG "}}
#define PIXELP          {{"GGGG "},{"G   G"},{"G   G"},{"GGGG "},{"G    "},{"G    "},{"G    "}}
#define PIXELQ          {{" GGG "},{"G   G"},{"G   G"},{"G   G"},{"G G G"},{"G  G "},{" GG G"}}
#define PIXELR          {{"GGGG "},{"G   G"},{"G   G"},{"GGGG "},{"G G  "},{"G  G "},{"G   G"}}
#define PIXELS          {{" GGGG"},{"G    "},{"G    "},{" GGG "},{"    G"},{"    G"},{"GGGG "}}
#define PIXELT          {{"GGGGG"},{"  G  "},{"  G  "},{"  G  "},{"  G  "},{"  G  "},{"  G  "}}
#define PIXELU          {{"G   G"},{"G   G"},{"G   G"},{"G   G"},{"G   G"},{"G   G"},{" GGG "}}
#define PIXELV          {{"G   G"},{"G   G"},{"G   G"},{"G   G"},{"G   G"},{" G G "},{"  G  "}}
#define PIXELY          {{"G   G"},{"G   G"},{"G   G"},{" G G "},{"  G  "},{"  G  "},{"  G  "}}*/

#define PIXELSLASH      {{LEDNOTEXT,   LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT}}
#define PIXELCOLON      {{LEDNOTEXT,   LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT}}
#define PIXELQUESTION   {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT}}
#define PIXEL0          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXEL1          {{LEDNOTEXT,   LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXEL2          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  }}
#define PIXEL3          {{LEDTEXT,     LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXEL4          {{LEDNOTEXT,   LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT}}
#define PIXEL5          {{LEDTEXT,     LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXEL6          {{LEDNOTEXT,   LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXEL7          {{LEDTEXT,     LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT}}
#define PIXEL8          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXEL9          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT}}
#define PIXELA          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  }}
#define PIXELC          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXELE          {{LEDTEXT,     LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  }}
#define PIXELG          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  }}
#define PIXELI          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXELM          {{LEDTEXT,     LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  }}
#define PIXELN          {{LEDTEXT,     LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  }}
#define PIXELO          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXELP          {{LEDTEXT,     LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT}}
#define PIXELQ          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDNOTEXT,  LEDTEXT  }}
#define PIXELR          {{LEDTEXT,     LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  }}
#define PIXELS          {{LEDNOTEXT,   LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXELT          {{LEDTEXT,     LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDTEXT  },{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT}}
#define PIXELU          {{LEDTEXT,     LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDTEXT,    LEDTEXT,    LEDNOTEXT}}
#define PIXELV          {{LEDTEXT,     LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT}}
#define PIXELY          {{LEDTEXT,     LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDTEXT,    LEDNOTEXT,  LEDNOTEXT,  LEDNOTEXT,  LEDTEXT  },{LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDTEXT,    LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT},{LEDNOTEXT,  LEDNOTEXT,  LEDTEXT,    LEDNOTEXT,  LEDNOTEXT}}
#endif // MACROS_H
